version: '2'
services:
    jhipstersampleapplication5-app:
        image: jhipstersampleapplication5
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication5-mysql:3306/jhipstersampleapplication5?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplication5-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplication5-mysql
